name: Generate Snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Clean dist folder
      - name: Clean dist folder
        run: rm -rf dist

      # 3️⃣ Generate the snake
      - uses: Platane/snk@v3
        with:
          github_user_name: thisismanikanta
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 4️⃣ Deploy to output branch
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output          # deploy branch
          folder: dist            # folder to deploy
          clean: true             # remove old files first
          commit_message: "Update Snake contribution grid"
